import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'EN' | 'PT' | 'FR';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('EN');

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  EN: {
    // Navigation
    'nav.home': 'Home',
    'nav.apartments': 'Apartments',
    'nav.about': 'About Us',
    
    // Hero Section
    'hero.title1': 'Luxury Living',
    'hero.title2': 'in Paradise',
    'hero.subtitle': 'Experience the essence of Madeira through our exceptional apartments, where natural beauty meets refined luxury.',
    'hero.cta.explore': 'Explore Our Apartments',
    'hero.cta.story': 'Our Story',
    
    // Home Page SEO
    'home.seo.title': 'Hibiscus - Luxury Apartments in Madeira',
    'home.seo.description': 'Discover your perfect luxury apartment in Madeira. Hibiscus offers stunning ocean and mountain views, premium amenities, and an unforgettable experience.',
    'home.seo.keywords': 'luxury apartments madeira, madeira vacation rentals, hibiscus madeira, ocean view apartments madeira, funchal apartments, luxury holiday homes madeira, madeira travel, madeira accommodation',

    // Home Page Features
    'home.features.title': 'Where Nature Meets Luxury',
    'home.features.subtitle': 'Experience the magic of Madeira through our carefully curated apartments, each designed to immerse you in the island\'s natural beauty while providing unparalleled comfort and style.',
    'home.features.mountain.title': 'Mountain Views',
    'home.features.mountain.desc': 'Wake up to breathtaking vistas of Madeira\'s dramatic peaks and lush valleys.',
    'home.features.ocean.title': 'Ocean Access',
    'home.features.ocean.desc': 'Steps away from pristine beaches and crystal-clear Atlantic waters.',
    'home.features.nature.title': 'Nature Immersion',
    'home.features.nature.desc': 'Surrounded by laurel forests and exotic gardens in a UNESCO World Heritage site.',
    'home.features.luxury.title': 'Luxury Amenities',
    'home.features.luxury.desc': 'Premium furnishings and modern conveniences for the perfect getaway.',
    
    // Featured Apartments
    'home.featured.title': 'Featured Apartments',
    'home.featured.subtitle': 'Discover our handpicked selection of luxury accommodations',
    
    // CTA Section
    'home.cta.title': 'Ready to Experience Paradise?',
    'home.cta.subtitle': 'Book your perfect getaway in Madeira today and create memories that will last a lifetime.',
    'home.cta.view': 'View All Apartments',
    'home.cta.learn': 'Learn More',
    
    // Apartments Page SEO
    'apartments.seo.title': 'Luxury Apartments in Madeira - Hibiscus',
    'apartments.seo.description': 'Explore our collection of luxury apartments in Madeira. Find your perfect getaway with stunning ocean and mountain views.',
    'apartments.seo.keywords': 'luxury apartments madeira, madeira apartments for rent, hibiscus apartments, all apartments madeira, madeira apartment collection, book apartment madeira, funchal luxury rentals',

    // Apartments Page
    'apartments.title': 'Our Luxury Apartments',
    'apartments.subtitle': 'Discover our carefully curated collection of premium accommodations, each offering a unique perspective on Madeira\'s natural beauty.',
    'apartments.notfound.title': 'Apartment Not Found',
    'apartments.notfound.subtitle': 'The apartment you\'re looking for doesn\'t exist.',
    'apartments.details.about': 'About This Space',
    'apartments.details.title': 'Apartment Details',
    'apartments.details.guests': 'guests',
    'apartments.details.bedroom': 'bedroom',
    'apartments.details.bedrooms': 'bedrooms',
    'apartments.details.bathroom': 'bathroom',
    'apartments.details.bathrooms': 'bathrooms',
    'apartments.details.location': 'Prime location',
    'apartments.amenities': 'Amenities',
    'apartments.location': 'Location',
    'apartments.video': 'Video Tour',
    'apartments.viewdetails': 'View Details',
    
    // Apartment Card
    'card.guests': 'guests',
    'card.bed': 'bed',
    'card.bath': 'bath',
    'card.night': '/night',
    'apartment.card.alt.prefix': 'Exterior view of',
    
    // Booking Calendar
    'booking.pernight': 'per night',
    'booking.checkin': 'Check-in',
    'booking.checkout': 'Check-out',
    'booking.guests': 'Guests',
    'booking.guest': 'Guest',
    'booking.nights': 'nights',
    'booking.total': 'Total',
    'booking.reserve': 'Reserve Now',
    'booking.notice': 'You won\'t be charged yet. This is a booking request.',
    
    // About Page SEO
    'about.seo.title': 'About Hibiscus - Our Story and Values',
    'about.seo.description': 'Learn about Hibiscus, our commitment to sustainable luxury, and our passion for creating unforgettable experiences in Madeira.',
    'about.seo.keywords': 'about hibiscus madeira, madeira luxury apartments story, sustainable tourism madeira, maria santos madeira, hibiscus values, eco-luxury madeira, responsible travel madeira',

    // About Page
    'about.hero.title': 'Our Story',
    'about.hero.subtitle': 'Born from a deep love for Madeira and a vision to share its magic with the world',
    'about.hero.image_alt': 'Lush, green mountains of Madeira island',
    'about.founder.image_alt': 'Maria Santos, founder of Hibiscus',
    'about.heart.title': 'The Heart of Hibiscus',
    'about.heart.p1': 'Hibiscus was born from a simple yet profound realization: that the most meaningful travel experiences happen when we truly connect with a place. Founded in 2020 by Maria Santos, a native Madeiran with a background in sustainable tourism, Hibiscus emerged from her desire to share the island\'s hidden gems with discerning travelers.',
    'about.heart.p2': 'Growing up surrounded by the laurel forests and dramatic coastlines of Madeira, Maria understood that the island\'s true luxury lies not in gilded surfaces, but in the raw beauty of its landscapes and the warmth of its people. This understanding became the foundation of Hibiscus - a collection of carefully curated apartments that serve as gateways to authentic Madeiran experiences.',
    'about.heart.p3': 'Today, Hibiscus represents more than luxury accommodation. We are stewards of place, committed to preserving the natural beauty that makes Madeira so special while sharing it with those who appreciate its unique magic.',
    'about.quote': 'Madeira taught me that true luxury is waking up to the sound of waves, breathing air perfumed by endemic flowers, and feeling completely at peace with the world around you.',
    'about.founder': 'Founder & CEO',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'Everything we do is guided by our deep respect for Madeira\'s natural beauty and our commitment to creating meaningful experiences for our guests.',
    'about.values.passion.title': 'Passion for Place',
    'about.values.passion.desc': 'We believe in the transformative power of place. Every apartment is chosen for its unique connection to Madeira\'s natural beauty.',
    'about.values.sustainable.title': 'Sustainable Luxury',
    'about.values.sustainable.desc': 'Our commitment to sustainability ensures that luxury and environmental responsibility go hand in hand.',
    'about.values.service.title': 'Personal Service',
    'about.values.service.desc': 'From the moment you inquire to the day you leave, our dedicated team ensures your experience is extraordinary.',
    'about.values.excellence.title': 'Excellence in Detail',
    'about.values.excellence.desc': 'Every detail matters, from the thread count of our linens to the organic local produce in our welcome baskets.',
    'about.philosophy.title': 'Our Philosophy',
    'about.philosophy.p1': 'We believe that the most luxurious experiences are those that connect us to something greater than ourselves. In Madeira, that connection is everywhere - in the ancient laurel forests, the dramatic volcanic peaks, and the endless expanse of the Atlantic Ocean.',
    'about.philosophy.p2': 'Our apartments are more than places to stay; they are carefully designed sanctuaries that frame and enhance your connection to this extraordinary island. Each space is chosen for its unique perspective on Madeira\'s natural beauty and designed to help you slow down, breathe deeply, and truly experience the magic of this place.',
    'about.philosophy.p3': 'This is luxury redefined - not as excess, but as essence. Not as separation from nature, but as harmony with it.',
    'about.team.title': 'Our Team',
    'about.team.subtitle': 'Behind every exceptional experience is a team of passionate individuals who call Madeira home and love sharing its beauty with the world.',
    'about.team.maria.role': 'Founder & CEO',
    'about.team.maria.bio': 'Native Madeiran with 15 years in sustainable tourism',
    'about.team.joao.name': 'João Silva',
    'about.team.joao.role': 'Guest Experience Manager',
    'about.team.joao.bio': 'Former luxury hotel manager, passionate about local culture',
    'about.team.ana.name': 'Ana Pereira',
    'about.team.ana.role': 'Property Curator',
    'about.team.ana.bio': 'Interior designer specializing in sustainable luxury',
    
    // Apartment Data
    'apt.ocean.name': 'Ocean Vista Suite',
    'apt.ocean.short': 'Luxury oceanfront apartment with panoramic Atlantic views',
    'apt.ocean.desc': 'Experience the ultimate in luxury living with our Ocean Vista Suite. This stunning oceanfront apartment offers breathtaking panoramic views of the Atlantic Ocean, featuring floor-to-ceiling windows that frame the endless horizon. The space is thoughtfully designed with natural materials, incorporating sustainable wood finishes and stone accents that reflect Madeira\'s volcanic heritage. The open-plan living area seamlessly flows onto a private terrace where you can enjoy spectacular sunsets and the gentle sound of waves.',
    'apt.mountain.name': 'Mountain Retreat Loft',
    'apt.mountain.short': 'Serene mountain-view loft surrounded by laurel forests',
    'apt.mountain.desc': 'Escape to our Mountain Retreat Loft, a serene sanctuary nestled in the heart of Madeira\'s lush laurel forests. This contemporary loft offers stunning mountain views and direct access to hiking trails through UNESCO World Heritage landscapes. The interior features exposed wooden beams, natural stone walls, and large skylights that flood the space with natural light. The design celebrates Madeira\'s rich natural heritage while providing all modern luxuries for a perfect retreat from urban life.',
    
    // Amenities
    'amenity.ocean.views': 'Panoramic ocean views',
    'amenity.terrace': 'Private terrace',
    'amenity.kitchen': 'Modern fully equipped kitchen',
    'amenity.bedding': 'Premium bedding and linens',
    'amenity.wifi': 'High-speed WiFi',
    'amenity.ac': 'Air conditioning',
    'amenity.concierge': 'Concierge service',
    'amenity.housekeeping': 'Daily housekeeping',
    'amenity.mountain.views': 'Mountain and forest views',
    'amenity.garden': 'Private garden access',
    'amenity.fireplace': 'Fireplace',
    'amenity.furniture': 'Designer furniture',
    'amenity.spa.bathroom': 'Spa-style bathroom',
    'amenity.hiking': 'Hiking trail access',
    'amenity.breakfast': 'Organic breakfast option',
    'amenity.yoga': 'Yoga and meditation space',
    
    // Footer
    'footer.description': 'Experience luxury living in Madeira\'s most beautiful locations with stunning ocean and mountain views.',
    'footer.quicklinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'footer.cancellation': 'Cancellation Policy',
    'footer.rights': 'All rights reserved.',
    'footer.madewith': 'Made with',
    'footer.inmadeira': 'in Madeira',
    
    // Contact Page SEO
    'contact.seo.title': 'Contact Hibiscus - Madeira Luxury Apartments',
    'contact.seo.description': 'Get in touch with Hibiscus to book your luxury apartment in Madeira or for any inquiries. We\'re here to help you plan your perfect stay.',
    'contact.seo.keywords': 'contact hibiscus madeira, book madeira apartments, madeira luxury rentals contact, hibiscus madeira address, madeira vacation inquiries, funchal apartment booking',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'re here to help you plan your perfect stay in Madeira',
    'contact.info.title': 'Get in Touch',
    'contact.info.address': 'Address',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Office Hours',
    'contact.info.weekdays': 'Monday - Friday',
    'contact.info.weekends': 'Saturday - Sunday',
    'contact.location': 'Our Location',
    'contact.form.title': 'Send us a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.selectsubject': 'Select a subject',
    'contact.form.subjects.booking': 'Booking Inquiry',
    'contact.form.subjects.information': 'General Information',
    'contact.form.subjects.support': 'Customer Support',
    'contact.form.subjects.partnership': 'Partnership',
    'contact.form.subjects.other': 'Other',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.success': 'Thank you for your message! We\'ll get back to you soon.',
    
    // Cookies
    'cookies.title': 'Cookie Preferences',
    'cookies.description': 'We use cookies to enhance your browsing experience, serve personalized content, and analyze our traffic. By clicking "Accept All", you consent to our use of cookies.',
    'cookies.acceptall': 'Accept All',
    'cookies.rejectall': 'Reject All',
    'cookies.customize': 'Customize Settings',
    'cookies.savepreferences': 'Save Preferences',
    'cookies.back': 'Back',
    'cookies.moreinfo': 'For more information, please read our',
    'cookies.policy': 'Cookie Policy',
    'cookies.necessary.title': 'Necessary Cookies',
    'cookies.necessary.desc': 'These cookies are essential for the website to function properly and cannot be disabled.',
    'cookies.analytics.title': 'Analytics Cookies',
    'cookies.analytics.desc': 'These cookies help us understand how visitors interact with our website.',
    'cookies.marketing.title': 'Marketing Cookies',
    'cookies.marketing.desc': 'These cookies are used to deliver personalized advertisements.',
    'cookies.functional.title': 'Functional Cookies',
    'cookies.functional.desc': 'These cookies enable enhanced functionality and personalization.',
    
    // Legal Pages SEO
    'privacy.seo.title': 'Privacy Policy - Hibiscus Madeira',
    'privacy.seo.description': 'Read our privacy policy to understand how we collect, use, and protect your personal information at Hibiscus Madeira.',
    'terms.seo.title': 'Terms of Service - Hibiscus Madeira',
    'terms.seo.description': 'Review our terms of service to understand the rules and guidelines for using our website and booking our luxury apartments.',
    'cookiepolicy.seo.title': 'Cookie Policy - Hibiscus Madeira',
    'cookiepolicy.seo.description': 'Learn about how we use cookies to enhance your browsing experience on the Hibiscus Madeira website.',
    'cancellation.seo.title': 'Cancellation Policy - Hibiscus Madeira',
    'cancellation.seo.description': 'Understand our cancellation policy for bookings at Hibiscus Madeira. Find details on refunds and modifications.',

    // Legal Pages
    'privacy.title': 'Privacy Policy',
    'privacy.lastupdated': 'Last updated',
    'privacy.introduction.title': 'Introduction',
    'privacy.introduction.content': 'At Hibiscus Madeira, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you use our services.',
    'privacy.datacollection.title': 'Information We Collect',
    'privacy.datacollection.intro': 'We collect information you provide directly to us, such as when you:',
    'privacy.datacollection.personal': 'Personal identification information (name, email, phone number)',
    'privacy.datacollection.booking': 'Booking and payment information',
    'privacy.datacollection.technical': 'Technical information (IP address, browser type, device information)',
    'privacy.datacollection.communication': 'Communication preferences and history',
    'privacy.datause.title': 'How We Use Your Information',
    'privacy.datause.intro': 'We use the information we collect to:',
    'privacy.datause.bookings': 'Process and manage your bookings',
    'privacy.datause.communication': 'Communicate with you about your reservations',
    'privacy.datause.improvement': 'Improve our services and website functionality',
    'privacy.datause.legal': 'Comply with legal obligations',
    'privacy.datasharing.title': 'Information Sharing',
    'privacy.datasharing.content': 'We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy or as required by law.',
    'privacy.cookies.title': 'Cookies and Tracking',
    'privacy.cookies.content': 'We use cookies and similar technologies to enhance your experience on our website. You can control cookie preferences through our cookie consent banner.',
    'privacy.rights.title': 'Your Rights',
    'privacy.rights.intro': 'Under applicable data protection laws, you have the right to:',
    'privacy.rights.access': 'Access your personal data',
    'privacy.rights.rectification': 'Rectify inaccurate data',
    'privacy.rights.erasure': 'Request deletion of your data',
    'privacy.rights.portability': 'Data portability',
    'privacy.rights.objection': 'Object to processing',
    'privacy.security.title': 'Data Security',
    'privacy.security.content': 'We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.',
    'privacy.contact.title': 'Contact Us',
    'privacy.contact.content': 'If you have any questions about this Privacy Policy or our data practices, please contact us:',
    
    'terms.title': 'Terms of Service',
    'terms.lastupdated': 'Last updated',
    'terms.acceptance.title': 'Acceptance of Terms',
    'terms.acceptance.content': 'By accessing and using Hibiscus Madeira services, you accept and agree to be bound by the terms and provision of this agreement.',
    'terms.services.title': 'Description of Services',
    'terms.services.content': 'Hibiscus Madeira provides luxury apartment rental services in Madeira, Portugal, including booking management, customer support, and accommodation services.',
    'terms.bookings.title': 'Booking Terms',
    'terms.bookings.intro': 'When making a booking with us:',
    'terms.bookings.confirmation': 'All bookings are subject to availability and confirmation',
    'terms.bookings.payment': 'Payment must be made according to our payment terms',
    'terms.bookings.checkin': 'Check-in and check-out times must be respected',
    'terms.bookings.checkout': 'Properties must be left in good condition',
    'terms.cancellation.title': 'Cancellation Policy',
    'terms.cancellation.content': 'Cancellations are subject to our cancellation policy, which varies by property and booking type. Please refer to our detailed Cancellation Policy for specific terms.',
    'terms.conduct.title': 'Guest Conduct',
    'terms.conduct.intro': 'Guests are expected to:',
    'terms.conduct.respect': 'Respect the property and neighbors',
    'terms.conduct.damage': 'Report any damage immediately',
    'terms.conduct.noise': 'Maintain reasonable noise levels',
    'terms.conduct.smoking': 'Follow smoking policies',
    'terms.conduct.pets': 'Comply with pet policies',
    'terms.liability.title': 'Limitation of Liability',
    'terms.liability.content': 'Hibiscus Madeira\'s liability is limited to the extent permitted by law. We are not responsible for any indirect, incidental, or consequential damages.',
    'terms.intellectual.title': 'Intellectual Property',
    'terms.intellectual.content': 'All content on our website, including text, graphics, logos, and images, is the property of Hibiscus Madeira and protected by copyright laws.',
    'terms.governing.title': 'Governing Law',
    'terms.governing.content': 'These terms are governed by the laws of Portugal. Any disputes will be resolved in the courts of Madeira, Portugal.',
    'terms.contact.title': 'Contact Information',
    'terms.contact.content': 'For questions about these Terms of Service, please contact us:',
    
    'cookiepolicy.title': 'Cookie Policy',
    'cookiepolicy.lastupdated': 'Last updated',
    'cookiepolicy.what.title': 'What are Cookies?',
    'cookiepolicy.what.content': 'Cookies are small text files that are placed on your device when you visit our website. They help us provide you with a better experience by remembering your preferences and analyzing how you use our site.',
    'cookiepolicy.types.title': 'Types of Cookies We Use',
    'cookiepolicy.types.necessary.title': 'Necessary Cookies',
    'cookiepolicy.types.necessary.content': 'These cookies are essential for the website to function properly. They enable basic functions like page navigation and access to secure areas.',
    'cookiepolicy.types.analytics.title': 'Analytics Cookies',
    'cookiepolicy.types.analytics.content': 'These cookies help us understand how visitors interact with our website by collecting and reporting information anonymously.',
    'cookiepolicy.types.marketing.title': 'Marketing Cookies',
    'cookiepolicy.types.marketing.content': 'These cookies are used to deliver advertisements more relevant to you and your interests.',
    'cookiepolicy.types.functional.title': 'Functional Cookies',
    'cookiepolicy.types.functional.content': 'These cookies enable the website to provide enhanced functionality and personalization.',
    'cookiepolicy.manage.title': 'Managing Cookies',
    'cookiepolicy.manage.content': 'You can control and manage cookies through our cookie consent banner or your browser settings. Note that disabling certain cookies may affect website functionality.',
    'cookiepolicy.thirdparty.title': 'Third-Party Cookies',
    'cookiepolicy.thirdparty.content': 'Some cookies are placed by third-party services that appear on our pages. We do not control these cookies.',
    'cookiepolicy.updates.title': 'Updates to This Policy',
    'cookiepolicy.updates.content': 'We may update this Cookie Policy from time to time. Any changes will be posted on this page with an updated revision date.',
    'cookiepolicy.contact.title': 'Contact Us',
    'cookiepolicy.contact.content': 'If you have any questions about our use of cookies, please contact us:',
    
    'cancellation.title': 'Cancellation Policy',
    'cancellation.lastupdated': 'Last updated',
    'cancellation.overview.title': 'Policy Overview',
    'cancellation.overview.content': 'Our cancellation policy varies depending on the property and rate selected. Please review the specific cancellation terms for your booking.',
    'cancellation.standard.title': 'Standard Cancellation Policy',
    'cancellation.standard.subtitle': 'Most of our properties follow this policy:',
    'cancellation.standard.free': 'Free cancellation up to 48 hours before check-in',
    'cancellation.standard.partial': '50% refund for cancellations 24-48 hours before check-in',
    'cancellation.standard.norefund': 'No refund for cancellations within 24 hours of check-in',
    'cancellation.flexible.title': 'Flexible Cancellation Policy',
    'cancellation.flexible.subtitle': 'Available for select properties:',
    'cancellation.flexible.free': 'Free cancellation up to 24 hours before check-in',
    'cancellation.flexible.partial': '50% refund for same-day cancellations',
    'cancellation.strict.title': 'Strict Cancellation Policy',
    'cancellation.strict.subtitle': 'Applies to peak season and special events:',
    'cancellation.strict.partial': '50% refund for cancellations up to 7 days before check-in',
    'cancellation.strict.norefund': 'No refund for cancellations within 7 days of check-in',
    'cancellation.process.title': 'How to Cancel',
    'cancellation.process.step1': 'Contact us via email or phone as soon as possible',
    'cancellation.process.step2': 'Provide your booking reference number',
    'cancellation.process.step3': 'We will confirm the cancellation and applicable refund',
    'cancellation.process.step4': 'Refunds are processed within 5-10 business days',
    'cancellation.exceptions.title': 'Exceptional Circumstances',
    'cancellation.exceptions.content': 'We may waive cancellation fees in cases of:',
    'cancellation.exceptions.weather': 'Severe weather conditions',
    'cancellation.exceptions.emergency': 'Medical emergencies',
    'cancellation.exceptions.government': 'Government-imposed travel restrictions',
    'cancellation.modifications.title': 'Booking Modifications',
    'cancellation.modifications.content': 'Changes to existing bookings are subject to availability and may incur additional charges. Contact us to discuss modification options.',
    'cancellation.contact.title': 'Need Help?',
    'cancellation.contact.content': 'For cancellations or questions about our policy, contact us:',
    'cancellation.contact.hours': 'Office Hours'
  },
  
  PT: {
    // Navigation
    'nav.home': 'Início',
    'nav.apartments': 'Apartamentos',
    'nav.about': 'Sobre Nós',
    
    // Hero Section
    'hero.title1': 'Vida de Luxo',
    'hero.title2': 'no Paraíso',
    'hero.subtitle': 'Experimente a essência da Madeira através dos nossos apartamentos excepcionais, onde a beleza natural encontra o luxo refinado.',
    'hero.cta.explore': 'Explore os Nossos Apartamentos',
    'hero.cta.story': 'A Nossa História',
    
    // Home Page SEO
    'home.seo.title': 'Hibiscus - Apartamentos de Luxo na Madeira',
    'home.seo.description': 'Descubra o seu apartamento de luxo perfeito na Madeira. A Hibiscus oferece vistas deslumbrantes sobre o oceano e a montanha, comodidades premium e uma experiência inesquecível.',
    'home.seo.keywords': 'apartamentos de luxo madeira, aluguer de férias madeira, hibiscus madeira, apartamentos com vista para o mar madeira, apartamentos funchal, casas de férias de luxo madeira, viajar para a madeira, alojamento na madeira',

    // Home Page Features
    'home.features.title': 'Onde a Natureza Encontra o Luxo',
    'home.features.subtitle': 'Experimente a magia da Madeira através dos nossos apartamentos cuidadosamente selecionados, cada um projetado para o imergir na beleza natural da ilha, proporcionando conforto e estilo incomparáveis.',
    'home.features.mountain.title': 'Vistas da Montanha',
    'home.features.mountain.desc': 'Acorde com vistas deslumbrantes dos picos dramáticos e vales verdejantes da Madeira.',
    'home.features.ocean.title': 'Acesso ao Oceano',
    'home.features.ocean.desc': 'A poucos passos de praias pristinas e águas cristalinas do Atlântico.',
    'home.features.nature.title': 'Imersão na Natureza',
    'home.features.nature.desc': 'Rodeado por florestas de loureiro e jardins exóticos num local Património Mundial da UNESCO.',
    'home.features.luxury.title': 'Comodidades de Luxo',
    'home.features.luxury.desc': 'Mobiliário premium e conveniências modernas para a escapadela perfeita.',
    
    // Featured Apartments
    'home.featured.title': 'Apartamentos em Destaque',
    'home.featured.subtitle': 'Descubra a nossa seleção cuidadosa de acomodações de luxo',
    
    // CTA Section
    'home.cta.title': 'Pronto para Experimentar o Paraíso?',
    'home.cta.subtitle': 'Reserve hoje a sua escapadela perfeita na Madeira e crie memórias que durarão para toda a vida.',
    'home.cta.view': 'Ver Todos os Apartamentos',
    'home.cta.learn': 'Saber Mais',
    
    // Apartments Page SEO
    'apartments.seo.title': 'Apartamentos de Luxo na Madeira - Hibiscus',
    'apartments.seo.description': 'Explore a nossa coleção de apartamentos de luxo na Madeira. Encontre a sua escapadela perfeita com vistas deslumbrantes sobre o oceano e a montanha.',
    'apartments.seo.keywords': 'apartamentos de luxo madeira, apartamentos para alugar madeira, apartamentos hibiscus, todos os apartamentos madeira, coleção de apartamentos madeira, reservar apartamento madeira, alugueres de luxo funchal',

    // Apartments Page
    'apartments.title': 'Os Nossos Apartamentos de Luxo',
    'apartments.subtitle': 'Descubra a nossa coleção cuidadosamente selecionada de acomodações premium, cada uma oferecendo uma perspetiva única sobre a beleza natural da Madeira.',
    'apartments.notfound.title': 'Apartamento Não Encontrado',
    'apartments.notfound.subtitle': 'O apartamento que procura não existe.',
    'apartments.details.about': 'Sobre Este Espaço',
    'apartments.details.title': 'Detalhes do Apartamento',
    'apartments.details.guests': 'hóspedes',
    'apartments.details.bedroom': 'quarto',
    'apartments.details.bedrooms': 'quartos',
    'apartments.details.bathroom': 'casa de banho',
    'apartments.details.bathrooms': 'casas de banho',
    'apartments.details.location': 'Localização privilegiada',
    'apartments.amenities': 'Comodidades',
    'apartments.location': 'Localização',
    'apartments.video': 'Tour Virtual',
    'apartments.viewdetails': 'Ver Detalhes',
    
    // Apartment Card
    'card.guests': 'hóspedes',
    'card.bed': 'quarto',
    'card.bath': 'wc',
    'card.night': '/noite',
    'apartment.card.alt.prefix': 'Vista exterior de',
    
    // Booking Calendar
    'booking.pernight': 'por noite',
    'booking.checkin': 'Check-in',
    'booking.checkout': 'Check-out',
    'booking.guests': 'Hóspedes',
    'booking.guest': 'Hóspede',
    'booking.nights': 'noites',
    'booking.total': 'Total',
    'booking.reserve': 'Reservar Agora',
    'booking.notice': 'Ainda não será cobrado. Esta é uma solicitação de reserva.',
    
    // About Page SEO
    'about.seo.title': 'Sobre a Hibiscus - A Nossa História e Valores',
    'about.seo.description': 'Saiba mais sobre a Hibiscus, o nosso compromisso com o luxo sustentável e a nossa paixão por criar experiências inesquecíveis na Madeira.',
    'about.seo.keywords': 'sobre a hibiscus madeira, história dos apartamentos de luxo na madeira, turismo sustentável madeira, maria santos madeira, valores da hibiscus, eco-luxo madeira, viagens responsáveis madeira',

    // About Page
    'about.hero.title': 'A Nossa História',
    'about.hero.subtitle': 'Nascida de um profundo amor pela Madeira e uma visão de partilhar a sua magia com o mundo',
    'about.hero.image_alt': 'Montanhas verdes e exuberantes da ilha da Madeira',
    'about.founder.image_alt': 'Maria Santos, fundadora da Hibiscus',
    'about.heart.title': 'O Coração da Hibiscus',
    'about.heart.p1': 'A Hibiscus nasceu de uma perceção simples mas profunda: as experiências de viagem mais significativas acontecem quando nos conectamos verdadeiramente com um lugar. Fundada em 2020 por Maria Santos, uma madeirense nativa com experiência em turismo sustentável, a Hibiscus surgiu do seu desejo de partilhar as joias escondidas da ilha com viajantes exigentes.',
    'about.heart.p2': 'Crescendo rodeada pelas florestas de loureiro e costas dramáticas da Madeira, Maria compreendeu que o verdadeiro luxo da ilha não reside em superfícies douradas, mas na beleza crua das suas paisagens e no calor do seu povo. Esta compreensão tornou-se a fundação da Hibiscus - uma coleção de apartamentos cuidadosamente selecionados que servem como portais para experiências madeirenses autênticas.',
    'about.heart.p3': 'Hoje, a Hibiscus representa mais do que acomodação de luxo. Somos guardiões do lugar, comprometidos em preservar a beleza natural que torna a Madeira tão especial, partilhando-a com aqueles que apreciam a sua magia única.',
    'about.quote': 'A Madeira ensinou-me que o verdadeiro luxo é acordar com o som das ondas, respirar ar perfumado por flores endémicas e sentir-se completamente em paz com o mundo ao nosso redor.',
    'about.founder': 'Fundadora e CEO',
    'about.values.title': 'Os Nossos Valores',
    'about.values.subtitle': 'Tudo o que fazemos é guiado pelo nosso profundo respeito pela beleza natural da Madeira e pelo nosso compromisso em criar experiências significativas para os nossos hóspedes.',
    'about.values.passion.title': 'Paixão pelo Lugar',
    'about.values.passion.desc': 'Acreditamos no poder transformador do lugar. Cada apartamento é escolhido pela sua conexão única com a beleza natural da Madeira.',
    'about.values.sustainable.title': 'Luxo Sustentável',
    'about.values.sustainable.desc': 'O nosso compromisso com a sustentabilidade garante que o luxo e a responsabilidade ambiental andem de mãos dadas.',
    'about.values.service.title': 'Serviço Pessoal',
    'about.values.service.desc': 'Desde o momento em que pergunta até ao dia em que parte, a nossa equipa dedicada garante que a sua experiência seja extraordinária.',
    'about.values.excellence.title': 'Excelência no Detalhe',
    'about.values.excellence.desc': 'Cada detalhe importa, desde a contagem de fios dos nossos lençóis até aos produtos locais orgânicos nos nossos cestos de boas-vindas.',
    'about.philosophy.title': 'A Nossa Filosofia',
    'about.philosophy.p1': 'Acreditamos que as experiências mais luxuosas são aquelas que nos conectam a algo maior do que nós próprios. Na Madeira, essa conexão está em todo o lado - nas antigas florestas de loureiro, nos picos vulcânicos dramáticos e na extensão infinita do Oceano Atlântico.',
    'about.philosophy.p2': 'Os nossos apartamentos são mais do que lugares para ficar; são santuários cuidadosamente projetados que enquadram e melhoram a sua conexão com esta ilha extraordinária. Cada espaço é escolhido pela sua perspetiva única sobre a beleza natural da Madeira e projetado para o ajudar a abrandar, respirar profundamente e verdadeiramente experimentar a magia deste lugar.',
    'about.philosophy.p3': 'Este é o luxo redefinido - não como excesso, mas como essência. Não como separação da natureza, mas como harmonia com ela.',
    'about.team.title': 'A Nossa Equipa',
    'about.team.subtitle': 'Por trás de cada experiência excecional está uma equipa de indivíduos apaixonados que chamam à Madeira casa e adoram partilhar a sua beleza com o mundo.',
    'about.team.maria.role': 'Fundadora e CEO',
    'about.team.maria.bio': 'Madeirense nativa com 15 anos em turismo sustentável',
    'about.team.joao.name': 'João Silva',
    'about.team.joao.role': 'Gestor de Experiência do Hóspede',
    'about.team.joao.bio': 'Ex-gestor de hotel de luxo, apaixonado pela cultura local',
    'about.team.ana.name': 'Ana Pereira',
    'about.team.ana.role': 'Curadora de Propriedades',
    'about.team.ana.bio': 'Designer de interiores especializada em luxo sustentável',
    
    // Apartment Data
    'apt.ocean.name': 'Suíte Vista Oceano',
    'apt.ocean.short': 'Apartamento de luxo à beira-mar com vistas panorâmicas do Atlântico',
    'apt.ocean.desc': 'Experimente o máximo em vida de luxo com a nossa Suíte Vista Oceano. Este deslumbrante apartamento à beira-mar oferece vistas panorâmicas de tirar o fôlego do Oceano Atlântico, com janelas do chão ao teto que enquadram o horizonte infinito. O espaço é cuidadosamente projetado com materiais naturais, incorporando acabamentos em madeira sustentável e acentos em pedra que refletem a herança vulcânica da Madeira. A área de estar em plano aberto flui perfeitamente para um terraço privado onde pode desfrutar de pores do sol espetaculares e do som suave das ondas.',
    'apt.mountain.name': 'Loft Retiro da Montanha',
    'apt.mountain.short': 'Loft sereno com vista para a montanha rodeado por florestas de loureiro',
    'apt.mountain.desc': 'Escape para o nosso Loft Retiro da Montanha, um santuário sereno aninhado no coração das exuberantes florestas de loureiro da Madeira. Este loft contemporâneo oferece vistas deslumbrantes da montanha e acesso direto a trilhos de caminhada através de paisagens Património Mundial da UNESCO. O interior apresenta vigas de madeira expostas, paredes de pedra natural e grandes claraboias que inundam o espaço com luz natural. O design celebra a rica herança natural da Madeira, proporcionando todos os luxos modernos para um retiro perfeito da vida urbana.',
    
    // Amenities
    'amenity.ocean.views': 'Vistas panorâmicas do oceano',
    'amenity.terrace': 'Terraço privado',
    'amenity.kitchen': 'Cozinha moderna totalmente equipada',
    'amenity.bedding': 'Roupa de cama e lençóis premium',
    'amenity.wifi': 'WiFi de alta velocidade',
    'amenity.ac': 'Ar condicionado',
    'amenity.concierge': 'Serviço de concierge',
    'amenity.housekeeping': 'Limpeza diária',
    'amenity.mountain.views': 'Vistas da montanha e floresta',
    'amenity.garden': 'Acesso a jardim privado',
    'amenity.fireplace': 'Lareira',
    'amenity.furniture': 'Mobiliário de design',
    'amenity.spa.bathroom': 'Casa de banho estilo spa',
    'amenity.hiking': 'Acesso a trilhos de caminhada',
    'amenity.breakfast': 'Opção de pequeno-almoço orgânico',
    'amenity.yoga': 'Espaço de yoga e meditação',
    
    // Footer
    'footer.description': 'Experimente a vida de luxo nos locais mais belos da Madeira com vistas deslumbrantes do oceano e da montanha.',
    'footer.quicklinks': 'Links Rápidos',
    'footer.contact': 'Contacto',
    'footer.legal': 'Legal',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'footer.cookies': 'Política de Cookies',
    'footer.cancellation': 'Política de Cancelamento',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.madewith': 'Feito com',
    'footer.inmadeira': 'na Madeira',
    
    // Contact Page SEO
    'contact.seo.title': 'Contactar a Hibiscus - Apartamentos de Luxo na Madeira',
    'contact.seo.description': 'Entre em contacto com a Hibiscus para reservar o seu apartamento de luxo na Madeira ou para qualquer questão. Estamos aqui para o ajudar a planear a sua estadia perfeita.',
    'contact.seo.keywords': 'contactar a hibiscus madeira, reservar apartamentos na madeira, contacto para alugueres de luxo na madeira, endereço da hibiscus madeira, questões sobre férias na madeira, reserva de apartamentos no funchal',

    // Contact Page
    'contact.title': 'Contacte-nos',
    'contact.subtitle': 'Estamos aqui para o ajudar a planear a sua estadia perfeita na Madeira',
    'contact.info.title': 'Entre em Contacto',
    'contact.info.address': 'Morada',
    'contact.info.phone': 'Telefone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Horário de Funcionamento',
    'contact.info.weekdays': 'Segunda - Sexta',
    'contact.info.weekends': 'Sábado - Domingo',
    'contact.location': 'A Nossa Localização',
    'contact.form.title': 'Envie-nos uma Mensagem',
    'contact.form.name': 'Nome Completo',
    'contact.form.email': 'Endereço de Email',
    'contact.form.subject': 'Assunto',
    'contact.form.selectsubject': 'Selecione um assunto',
    'contact.form.subjects.booking': 'Pedido de Reserva',
    'contact.form.subjects.information': 'Informação Geral',
    'contact.form.subjects.support': 'Apoio ao Cliente',
    'contact.form.subjects.partnership': 'Parceria',
    'contact.form.subjects.other': 'Outro',
    'contact.form.message': 'Mensagem',
    'contact.form.send': 'Enviar Mensagem',
    'contact.form.success': 'Obrigado pela sua mensagem! Entraremos em contacto em breve.',
    
    // Cookies
    'cookies.title': 'Preferências de Cookies',
    'cookies.description': 'Utilizamos cookies para melhorar a sua experiência de navegação, servir conteúdo personalizado e analisar o nosso tráfego. Ao clicar em "Aceitar Todos", consente o uso de cookies.',
    'cookies.acceptall': 'Aceitar Todos',
    'cookies.rejectall': 'Rejeitar Todos',
    'cookies.customize': 'Personalizar Definições',
    'cookies.savepreferences': 'Guardar Preferências',
    'cookies.back': 'Voltar',
    'cookies.moreinfo': 'Para mais informações, leia a nossa',
    'cookies.policy': 'Política de Cookies',
    'cookies.necessary.title': 'Cookies Necessários',
    'cookies.necessary.desc': 'Estes cookies são essenciais para o funcionamento adequado do website e não podem ser desativados.',
    'cookies.analytics.title': 'Cookies de Análise',
    'cookies.analytics.desc': 'Estes cookies ajudam-nos a compreender como os visitantes interagem com o nosso website.',
    'cookies.marketing.title': 'Cookies de Marketing',
    'cookies.marketing.desc': 'Estes cookies são usados para fornecer anúncios personalizados.',
    'cookies.functional.title': 'Cookies Funcionais',
    'cookies.functional.desc': 'Estes cookies permitem funcionalidades melhoradas e personalização.',
    
    // Legal Pages SEO
    'privacy.seo.title': 'Política de Privacidade - Hibiscus Madeira',
    'privacy.seo.description': 'Leia a nossa política de privacidade para entender como recolhemos, usamos e protegemos as suas informações pessoais na Hibiscus Madeira.',
    'terms.seo.title': 'Termos de Serviço - Hibiscus Madeira',
    'terms.seo.description': 'Reveja os nossos termos de serviço para entender as regras e diretrizes para usar o nosso site e reservar os nossos apartamentos de luxo.',
    'cookiepolicy.seo.title': 'Política de Cookies - Hibiscus Madeira',
    'cookiepolicy.seo.description': 'Saiba como usamos cookies para melhorar a sua experiência de navegação no site da Hibiscus Madeira.',
    'cancellation.seo.title': 'Política de Cancelamento - Hibiscus Madeira',
    'cancellation.seo.description': 'Entenda a nossa política de cancelamento para reservas na Hibiscus Madeira. Encontre detalhes sobre reembolsos e modificações.',

    // Legal Pages
    'privacy.title': 'Política de Privacidade',
    'privacy.lastupdated': 'Última atualização',
    'privacy.introduction.title': 'Introdução',
    'privacy.introduction.content': 'Na Hibiscus Madeira, estamos comprometidos em proteger a sua privacidade e garantir a segurança das suas informações pessoais. Esta Política de Privacidade explica como recolhemos, usamos e protegemos os seus dados quando utiliza os nossos serviços.',
    'privacy.datacollection.title': 'Informações que Recolhemos',
    'privacy.datacollection.intro': 'Recolhemos informações que nos fornece diretamente, como quando:',
    'privacy.datacollection.personal': 'Informações de identificação pessoal (nome, email, número de telefone)',
    'privacy.datacollection.booking': 'Informações de reserva e pagamento',
    'privacy.datacollection.technical': 'Informações técnicas (endereço IP, tipo de navegador, informações do dispositivo)',
    'privacy.datacollection.communication': 'Preferências e histórico de comunicação',
    'privacy.datause.title': 'Como Usamos as Suas Informações',
    'privacy.datause.intro': 'Usamos as informações que recolhemos para:',
    'privacy.datause.bookings': 'Processar e gerir as suas reservas',
    'privacy.datause.communication': 'Comunicar consigo sobre as suas reservas',
    'privacy.datause.improvement': 'Melhorar os nossos serviços e funcionalidade do website',
    'privacy.datause.legal': 'Cumprir obrigações legais',
    'privacy.datasharing.title': 'Partilha de Informações',
    'privacy.datasharing.content': 'Não vendemos, trocamos ou transferimos as suas informações pessoais para terceiros sem o seu consentimento, exceto conforme descrito nesta política ou conforme exigido por lei.',
    'privacy.cookies.title': 'Cookies e Rastreamento',
    'privacy.cookies.content': 'Utilizamos cookies e tecnologias similares para melhorar a sua experiência no nosso website. Pode controlar as preferências de cookies através do nosso banner de consentimento.',
    'privacy.rights.title': 'Os Seus Direitos',
    'privacy.rights.intro': 'Sob as leis de proteção de dados aplicáveis, tem o direito de:',
    'privacy.rights.access': 'Aceder aos seus dados pessoais',
    'privacy.rights.rectification': 'Retificar dados incorretos',
    'privacy.rights.erasure': 'Solicitar a eliminação dos seus dados',
    'privacy.rights.portability': 'Portabilidade de dados',
    'privacy.rights.objection': 'Objetar ao processamento',
    'privacy.security.title': 'Segurança de Dados',
    'privacy.security.content': 'Implementamos medidas técnicas e organizacionais apropriadas para proteger as suas informações pessoais contra acesso não autorizado, alteração, divulgação ou destruição.',
    'privacy.contact.title': 'Contacte-nos',
    'privacy.contact.content': 'Se tiver questões sobre esta Política de Privacidade ou as nossas práticas de dados, contacte-nos:',
    
    'terms.title': 'Termos de Serviço',
    'terms.lastupdated': 'Última atualização',
    'terms.acceptance.title': 'Aceitação dos Termos',
    'terms.acceptance.content': 'Ao aceder e usar os serviços da Hibiscus Madeira, aceita e concorda em ficar vinculado aos termos e disposições deste acordo.',
    'terms.services.title': 'Descrição dos Serviços',
    'terms.services.content': 'A Hibiscus Madeira fornece serviços de aluguer de apartamentos de luxo na Madeira, Portugal, incluindo gestão de reservas, apoio ao cliente e serviços de acomodação.',
    'terms.bookings.title': 'Termos de Reserva',
    'terms.bookings.intro': 'Ao fazer uma reserva connosco:',
    'terms.bookings.confirmation': 'Todas as reservas estão sujeitas a disponibilidade e confirmação',
    'terms.bookings.payment': 'O pagamento deve ser feito de acordo com os nossos termos de pagamento',
    'terms.bookings.checkin': 'Os horários de check-in e check-out devem ser respeitados',
    'terms.bookings.checkout': 'As propriedades devem ser deixadas em boas condições',
    'terms.cancellation.title': 'Política de Cancelamento',
    'terms.cancellation.content': 'Os cancelamentos estão sujeitos à nossa política de cancelamento, que varia por propriedade e tipo de reserva. Consulte a nossa Política de Cancelamento detalhada para termos específicos.',
    'terms.conduct.title': 'Conduta do Hóspede',
    'terms.conduct.intro': 'Os hóspedes devem:',
    'terms.conduct.respect': 'Respeitar a propriedade e os vizinhos',
    'terms.conduct.damage': 'Reportar qualquer dano imediatamente',
    'terms.conduct.noise': 'Manter níveis de ruído razoáveis',
    'terms.conduct.smoking': 'Seguir as políticas de fumo',
    'terms.conduct.pets': 'Cumprir as políticas de animais',
    'terms.liability.title': 'Limitação de Responsabilidade',
    'terms.liability.content': 'A responsabilidade da Hibiscus Madeira é limitada na medida permitida por lei. Não somos responsáveis por quaisquer danos indiretos, incidentais ou consequenciais.',
    'terms.intellectual.title': 'Propriedade Intelectual',
    'terms.intellectual.content': 'Todo o conteúdo do nosso website, incluindo texto, gráficos, logótipos e imagens, é propriedade da Hibiscus Madeira e protegido por leis de direitos autorais.',
    'terms.governing.title': 'Lei Aplicável',
    'terms.governing.content': 'Estes termos são regidos pelas leis de Portugal. Quaisquer disputas serão resolvidas nos tribunais da Madeira, Portugal.',
    'terms.contact.title': 'Informações de Contacto',
    'terms.contact.content': 'Para questões sobre estes Termos de Serviço, contacte-nos:',
    
    'cookiepolicy.title': 'Política de Cookies',
    'cookiepolicy.lastupdated': 'Última atualização',
    'cookiepolicy.what.title': 'O que são Cookies?',
    'cookiepolicy.what.content': 'Cookies são pequenos ficheiros de texto que são colocados no seu dispositivo quando visita o nosso website. Ajudam-nos a fornecer uma melhor experiência ao lembrar as suas preferências e analisar como usa o nosso site.',
    'cookiepolicy.types.title': 'Tipos de Cookies que Usamos',
    'cookiepolicy.types.necessary.title': 'Cookies Necessários',
    'cookiepolicy.types.necessary.content': 'Estes cookies são essenciais para o funcionamento adequado do website. Permitem funções básicas como navegação de páginas e acesso a áreas seguras.',
    'cookiepolicy.types.analytics.title': 'Cookies de Análise',
    'cookiepolicy.types.analytics.content': 'Estes cookies ajudam-nos a compreender como os visitantes interagem com o nosso website ao recolher e reportar informações anonimamente.',
    'cookiepolicy.types.marketing.title': 'Cookies de Marketing',
    'cookiepolicy.types.marketing.content': 'Estes cookies são usados para fornecer anúncios mais relevantes para si e os seus interesses.',
    'cookiepolicy.types.functional.title': 'Cookies Funcionais',
    'cookiepolicy.types.functional.content': 'Estes cookies permitem que o website forneça funcionalidade melhorada e personalização.',
    'cookiepolicy.manage.title': 'Gerir Cookies',
    'cookiepolicy.manage.content': 'Pode controlar e gerir cookies através do nosso banner de consentimento ou das configurações do seu navegador. Note que desativar certos cookies pode afetar a funcionalidade do website.',
    'cookiepolicy.thirdparty.title': 'Cookies de Terceiros',
    'cookiepolicy.thirdparty.content': 'Alguns cookies são colocados por serviços de terceiros que aparecem nas nossas páginas. Não controlamos estes cookies.',
    'cookiepolicy.updates.title': 'Atualizações desta Política',
    'cookiepolicy.updates.content': 'Podemos atualizar esta Política de Cookies de tempos em tempos. Quaisquer alterações serão publicadas nesta página com uma data de revisão atualizada.',
    'cookiepolicy.contact.title': 'Contacte-nos',
    'cookiepolicy.contact.content': 'Se tiver questões sobre o nosso uso de cookies, contacte-nos:',
    
    'cancellation.title': 'Política de Cancelamento',
    'cancellation.lastupdated': 'Última atualização',
    'cancellation.overview.title': 'Visão Geral da Política',
    'cancellation.overview.content': 'A nossa política de cancelamento varia dependendo da propriedade e tarifa selecionada. Reveja os termos específicos de cancelamento para a sua reserva.',
    'cancellation.standard.title': 'Política de Cancelamento Padrão',
    'cancellation.standard.subtitle': 'A maioria das nossas propriedades segue esta política:',
    'cancellation.standard.free': 'Cancelamento gratuito até 48 horas antes do check-in',
    'cancellation.standard.partial': '50% de reembolso para cancelamentos 24-48 horas antes do check-in',
    'cancellation.standard.norefund': 'Sem reembolso para cancelamentos dentro de 24 horas do check-in',
    'cancellation.flexible.title': 'Política de Cancelamento Flexível',
    'cancellation.flexible.subtitle': 'Disponível para propriedades selecionadas:',
    'cancellation.flexible.free': 'Cancelamento gratuito até 24 horas antes do check-in',
    'cancellation.flexible.partial': '50% de reembolso para cancelamentos no mesmo dia',
    'cancellation.strict.title': 'Política de Cancelamento Rigorosa',
    'cancellation.strict.subtitle': 'Aplica-se à época alta e eventos especiais:',
    'cancellation.strict.partial': '50% de reembolso para cancelamentos até 7 dias antes do check-in',
    'cancellation.strict.norefund': 'Sem reembolso para cancelamentos dentro de 7 dias do check-in',
    'cancellation.process.title': 'Como Cancelar',
    'cancellation.process.step1': 'Contacte-nos por email ou telefone o mais rápido possível',
    'cancellation.process.step2': 'Forneça o seu número de referência de reserva',
    'cancellation.process.step3': 'Confirmaremos o cancelamento e o reembolso aplicável',
    'cancellation.process.step4': 'Os reembolsos são processados dentro de 5-10 dias úteis',
    'cancellation.exceptions.title': 'Circunstâncias Excecionais',
    'cancellation.exceptions.content': 'Podemos dispensar taxas de cancelamento em casos de:',
    'cancellation.exceptions.weather': 'Condições meteorológicas severas',
    'cancellation.exceptions.emergency': 'Emergências médicas',
    'cancellation.exceptions.government': 'Restrições de viagem impostas pelo governo',
    'cancellation.modifications.title': 'Modificações de Reserva',
    'cancellation.modifications.content': 'Alterações a reservas existentes estão sujeitas a disponibilidade e podem incorrer em taxas adicionais. Contacte-nos para discutir opções de modificação.',
    'cancellation.contact.title': 'Precisa de Ajuda?',
    'cancellation.contact.content': 'Para cancelamentos ou questões sobre a nossa política, contacte-nos:',
    'cancellation.contact.hours': 'Horário de Funcionamento'
  },
  
  FR: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.apartments': 'Appartements',
    'nav.about': 'À Propos',
    
    // Hero Section
    'hero.title1': 'Vie de Luxe',
    'hero.title2': 'au Paradis',
    'hero.subtitle': 'Découvrez l\'essence de Madère à travers nos appartements exceptionnels, où la beauté naturelle rencontre le luxe raffiné.',
    'hero.cta.explore': 'Explorez Nos Appartements',
    'hero.cta.story': 'Notre Histoire',
    
    // Home Page SEO
    'home.seo.title': 'Hibiscus - Appartements de Luxe à Madère',
    'home.seo.description': 'Découvrez votre appartement de luxe idéal à Madère. Hibiscus propose des vues imprenables sur l\'océan et la montagne, des équipements haut de gamme et une expérience inoubliable.',
    'home.seo.keywords': 'appartements de luxe madère, locations de vacances madère, hibiscus madère, appartements vue mer madère, appartements funchal, maisons de vacances de luxe madère, voyager à madère, hébergement à madère',

    // Home Page Features
    'home.features.title': 'Où la Nature Rencontre le Luxe',
    'home.features.subtitle': 'Découvrez la magie de Madère à travers nos appartements soigneusement sélectionnés, chacun conçu pour vous immerger dans la beauté naturelle de l\'île tout en offrant un confort et un style inégalés.',
    'home.features.mountain.title': 'Vues sur la Montagne',
    'home.features.mountain.desc': 'Réveillez-vous avec des vues à couper le souffle sur les pics dramatiques et les vallées luxuriantes de Madère.',
    'home.features.ocean.title': 'Accès à l\'Océan',
    'home.features.ocean.desc': 'À quelques pas de plages pristines et d\'eaux cristallines de l\'Atlantique.',
    'home.features.nature.title': 'Immersion Nature',
    'home.features.nature.desc': 'Entouré de forêts de lauriers et de jardins exotiques dans un site du patrimoine mondial de l\'UNESCO.',
    'home.features.luxury.title': 'Équipements de Luxe',
    'home.features.luxury.desc': 'Mobilier haut de gamme et commodités modernes pour l\'escapade parfaite.',
    
    // Featured Apartments
    'home.featured.title': 'Appartements en Vedette',
    'home.featured.subtitle': 'Découvrez notre sélection soigneusement choisie d\'hébergements de luxe',
    
    // CTA Section
    'home.cta.title': 'Prêt à Découvrir le Paradis?',
    'home.cta.subtitle': 'Réservez votre escapade parfaite à Madère aujourd\'hui et créez des souvenirs qui dureront toute une vie.',
    'home.cta.view': 'Voir Tous les Appartements',
    'home.cta.learn': 'En Savoir Plus',
    
    // Apartments Page SEO
    'apartments.seo.title': 'Appartements de Luxe à Madère - Hibiscus',
    'apartments.seo.description': 'Explorez notre collection d\'appartements de luxe à Madère. Trouvez votre escapade idéale avec des vues imprenables sur l\'océan et la montagne.',
    'apartments.seo.keywords': 'appartements de luxe madère, appartements à louer madère, appartements hibiscus, tous les appartements madère, collection d\'appartements madère, réserver un appartement madère, locations de luxe funchal',

    // Apartments Page
    'apartments.title': 'Nos Appartements de Luxe',
    'apartments.subtitle': 'Découvrez notre collection soigneusement sélectionnée d\'hébergements premium, chacun offrant une perspective unique sur la beauté naturelle de Madère.',
    'apartments.notfound.title': 'Appartement Introuvable',
    'apartments.notfound.subtitle': 'L\'appartement que vous recherchez n\'existe pas.',
    'apartments.details.about': 'À Propos de Cet Espace',
    'apartments.details.title': 'Détails de l\'Appartement',
    'apartments.details.guests': 'invités',
    'apartments.details.bedroom': 'chambre',
    'apartments.details.bedrooms': 'chambres',
    'apartments.details.bathroom': 'salle de bain',
    'apartments.details.bathrooms': 'salles de bain',
    'apartments.details.location': 'Emplacement privilégié',
    'apartments.amenities': 'Équipements',
    'apartments.location': 'Emplacement',
    'apartments.video': 'Visite Virtuelle',
    'apartments.viewdetails': 'Voir les Détails',
    
    // Apartment Card
    'card.guests': 'invités',
    'card.bed': 'lit',
    'card.bath': 'bain',
    'card.night': '/nuit',
    'apartment.card.alt.prefix': 'Vue extérieure de',
    
    // Booking Calendar
    'booking.pernight': 'par nuit',
    'booking.checkin': 'Arrivée',
    'booking.checkout': 'Départ',
    'booking.guests': 'Invités',
    'booking.guest': 'Invité',
    'booking.nights': 'nuits',
    'booking.total': 'Total',
    'booking.reserve': 'Réserver Maintenant',
    'booking.notice': 'Vous ne serez pas encore facturé. Ceci est une demande de réservation.',
    
    // About Page SEO
    'about.seo.title': 'À Propos d\'Hibiscus - Notre Histoire et Nos Valeurs',
    'about.seo.description': 'Découvrez Hibiscus, notre engagement pour un luxe durable et notre passion pour la création d\'expériences inoubliables à Madère.',
    'about.seo.keywords': 'à propos d\'hibiscus madère, histoire des appartements de luxe à madère, tourisme durable madère, maria santos madère, valeurs d\'hibiscus, éco-luxe madère, voyages responsables madère',

    // About Page
    'about.hero.title': 'Notre Histoire',
    'about.hero.subtitle': 'Née d\'un amour profond pour Madère et d\'une vision de partager sa magie avec le monde',
    'about.hero.image_alt': 'Montagnes verdoyantes et luxuriantes de l\'île de Madère',
    'about.founder.image_alt': 'Maria Santos, fondatrice d\'Hibiscus',
    'about.heart.title': 'Le Cœur d\'Hibiscus',
    'about.heart.p1': 'Hibiscus est née d\'une réalisation simple mais profonde : les expériences de voyage les plus significatives se produisent lorsque nous nous connectons vraiment avec un lieu. Fondée en 2020 par Maria Santos, une native de Madère avec une expérience en tourisme durable, Hibiscus a émergé de son désir de partager les joyaux cachés de l\'île avec des voyageurs exigeants.',
    'about.heart.p2': 'Ayant grandi entourée par les forêts de lauriers et les côtes dramatiques de Madère, Maria a compris que le véritable luxe de l\'île ne réside pas dans les surfaces dorées, mais dans la beauté brute de ses paysages et la chaleur de son peuple. Cette compréhension est devenue la fondation d\'Hibiscus - une collection d\'appartements soigneusement sélectionnés qui servent de portails vers des expériences madériennes authentiques.',
    'about.heart.p3': 'Aujourd\'hui, Hibiscus représente plus qu\'un hébergement de luxe. Nous sommes des gardiens du lieu, engagés à préserver la beauté naturelle qui rend Madère si spéciale tout en la partageant avec ceux qui apprécient sa magie unique.',
    'about.quote': 'Madère m\'a appris que le véritable luxe, c\'est se réveiller au son des vagues, respirer un air parfumé par des fleurs endémiques et se sentir complètement en paix avec le monde qui nous entoure.',
    'about.founder': 'Fondatrice et PDG',
    'about.values.title': 'Nos Valeurs',
    'about.values.subtitle': 'Tout ce que nous faisons est guidé par notre profond respect pour la beauté naturelle de Madère et notre engagement à créer des expériences significatives pour nos invités.',
    'about.values.passion.title': 'Passion pour le Lieu',
    'about.values.passion.desc': 'Nous croyons au pouvoir transformateur du lieu. Chaque appartement est choisi pour sa connexion unique avec la beauté naturelle de Madère.',
    'about.values.sustainable.title': 'Luxe Durable',
    'about.values.sustainable.desc': 'Notre engagement envers la durabilité garantit que le luxe et la responsabilité environnementale vont de pair.',
    'about.values.service.title': 'Service Personnel',
    'about.values.service.desc': 'Du moment où vous vous renseignez au jour où vous partez, notre équipe dévouée s\'assure que votre expérience soit extraordinaire.',
    'about.values.excellence.title': 'Excellence dans le Détail',
    'about.values.excellence.desc': 'Chaque détail compte, du nombre de fils de nos draps aux produits locaux biologiques dans nos paniers de bienvenue.',
    'about.philosophy.title': 'Notre Philosophie',
    'about.philosophy.p1': 'Nous croyons que les expériences les plus luxueuses sont celles qui nous connectent à quelque chose de plus grand que nous-mêmes. À Madère, cette connexion est partout - dans les anciennes forêts de lauriers, les pics volcaniques dramatiques et l\'étendue infinie de l\'océan Atlantique.',
    'about.philosophy.p2': 'Nos appartements sont plus que des lieux de séjour ; ce sont des sanctuaires soigneusement conçus qui encadrent et améliorent votre connexion avec cette île extraordinaire. Chaque espace est choisi pour sa perspective unique sur la beauté naturelle de Madère et conçu pour vous aider à ralentir, respirer profondément et vraiment expérimenter la magie de ce lieu.',
    'about.philosophy.p3': 'C\'est le luxe redéfini - non pas comme excès, mais comme essence. Non pas comme séparation de la nature, mais comme harmonie avec elle.',
    'about.team.title': 'Notre Équipe',
    'about.team.subtitle': 'Derrière chaque expérience exceptionnelle se trouve une équipe d\'individus passionnés qui appellent Madère leur maison et adorent partager sa beauté avec le monde.',
    'about.team.maria.role': 'Fondatrice et PDG',
    'about.team.maria.bio': 'Native de Madère avec 15 ans d\'expérience en tourisme durable',
    'about.team.joao.name': 'João Silva',
    'about.team.joao.role': 'Responsable Expérience Client',
    'about.team.joao.bio': 'Ancien directeur d\'hôtel de luxe, passionné par la culture locale',
    'about.team.ana.name': 'Ana Pereira',
    'about.team.ana.role': 'Curatrice de Propriétés',
    'about.team.ana.bio': 'Designer d\'intérieur spécialisée en luxe durable',
    
    // Apartment Data
    'apt.ocean.name': 'Suite Vue Océan',
    'apt.ocean.short': 'Appartement de luxe en bord de mer avec vues panoramiques sur l\'Atlantique',
    'apt.ocean.desc': 'Découvrez le summum de la vie de luxe avec notre Suite Vue Océan. Cet appartement en bord de mer époustouflant offre des vues panoramiques à couper le souffle sur l\'océan Atlantique, avec des baies vitrées du sol au plafond qui encadrent l\'horizon infini. L\'espace est soigneusement conçu avec des matériaux naturels, incorporant des finitions en bois durable et des accents de pierre qui reflètent l\'héritage volcanique de Madère. L\'espace de vie ouvert s\'étend harmonieusement sur une terrasse privée où vous pouvez profiter de couchers de soleil spectaculaires et du doux bruit des vagues.',
    'apt.mountain.name': 'Loft Retraite Montagne',
    'apt.mountain.short': 'Loft serein avec vue sur la montagne entouré de forêts de lauriers',
    'apt.mountain.desc': 'Évadez-vous dans notre Loft Retraite Montagne, un sanctuaire serein niché au cœur des luxuriantes forêts de lauriers de Madère. Ce loft contemporain offre des vues magnifiques sur la montagne et un accès direct aux sentiers de randonnée à travers les paysages du patrimoine mondial de l\'UNESCO. L\'intérieur présente des poutres en bois apparentes, des murs en pierre naturelle et de grandes lucarnes qui inondent l\'espace de lumière naturelle. Le design célèbre le riche patrimoine naturel de Madère tout en offrant tous les luxes modernes pour une retraite parfaite de la vie urbaine.',
    
    // Amenities
    'amenity.ocean.views': 'Vues panoramiques sur l\'océan',
    'amenity.terrace': 'Terrasse privée',
    'amenity.kitchen': 'Cuisine moderne entièrement équipée',
    'amenity.bedding': 'Literie et draps haut de gamme',
    'amenity.wifi': 'WiFi haut débit',
    'amenity.ac': 'Climatisation',
    'amenity.concierge': 'Service de conciergerie',
    'amenity.housekeeping': 'Ménage quotidien',
    'amenity.mountain.views': 'Vues sur la montagne et la forêt',
    'amenity.garden': 'Accès jardin privé',
    'amenity.fireplace': 'Cheminée',
    'amenity.furniture': 'Mobilier design',
    'amenity.spa.bathroom': 'Salle de bain style spa',
    'amenity.hiking': 'Accès sentiers de randonnée',
    'amenity.breakfast': 'Option petit-déjeuner bio',
    'amenity.yoga': 'Espace yoga et méditation',
    
    // Footer
    'footer.description': 'Découvrez la vie de luxe dans les plus beaux endroits de Madère avec des vues imprenables sur l\'océan et la montagne.',
    'footer.quicklinks': 'Liens Rapides',
    'footer.contact': 'Contact',
    'footer.legal': 'Légal',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions de Service',
    'footer.cookies': 'Politique des Cookies',
    'footer.cancellation': 'Politique d\'Annulation',
    'footer.rights': 'Tous droits réservés.',
    'footer.madewith': 'Fait avec',
    'footer.inmadeira': 'à Madère',
    
    // Contact Page SEO
    'contact.seo.title': 'Contacter Hibiscus - Appartements de Luxe à Madère',
    'contact.seo.description': 'Prenez contact avec Hibiscus pour réserver votre appartement de luxe à Madère ou pour toute demande. Nous sommes là pour vous aider à planifier votre séjour parfait.',
    'contact.seo.keywords': 'contacter hibiscus madère, réserver appartements madère, contact locations de luxe madère, adresse hibiscus madère, demandes de renseignements vacances madère, réservation appartement funchal',

    // Contact Page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous sommes là pour vous aider à planifier votre séjour parfait à Madère',
    'contact.info.title': 'Prenez Contact',
    'contact.info.address': 'Adresse',
    'contact.info.phone': 'Téléphone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Heures d\'Ouverture',
    'contact.info.weekdays': 'Lundi - Vendredi',
    'contact.info.weekends': 'Samedi - Dimanche',
    'contact.location': 'Notre Emplacement',
    'contact.form.title': 'Envoyez-nous un Message',
    'contact.form.name': 'Nom Complet',
    'contact.form.email': 'Adresse Email',
    'contact.form.subject': 'Sujet',
    'contact.form.selectsubject': 'Sélectionnez un sujet',
    'contact.form.subjects.booking': 'Demande de Réservation',
    'contact.form.subjects.information': 'Information Générale',
    'contact.form.subjects.support': 'Support Client',
    'contact.form.subjects.partnership': 'Partenariat',
    'contact.form.subjects.other': 'Autre',
    'contact.form.message': 'Message',
    'contact.form.send': 'Envoyer le Message',
    'contact.form.success': 'Merci pour votre message ! Nous vous répondrons bientôt.',
    
    // Cookies
    'cookies.title': 'Préférences des Cookies',
    'cookies.description': 'Nous utilisons des cookies pour améliorer votre expérience de navigation, servir du contenu personnalisé et analyser notre trafic. En cliquant sur "Accepter Tout", vous consentez à notre utilisation des cookies.',
    'cookies.acceptall': 'Accepter Tout',
    'cookies.rejectall': 'Rejeter Tout',
    'cookies.customize': 'Personnaliser les Paramètres',
    'cookies.savepreferences': 'Sauvegarder les Préférences',
    'cookies.back': 'Retour',
    'cookies.moreinfo': 'Pour plus d\'informations, veuillez lire notre',
    'cookies.policy': 'Politique des Cookies',
    'cookies.necessary.title': 'Cookies Nécessaires',
    'cookies.necessary.desc': 'Ces cookies sont essentiels au bon fonctionnement du site web et ne peuvent pas être désactivés.',
    'cookies.analytics.title': 'Cookies d\'Analyse',
    'cookies.analytics.desc': 'Ces cookies nous aident à comprendre comment les visiteurs interagissent avec notre site web.',
    'cookies.marketing.title': 'Cookies Marketing',
    'cookies.marketing.desc': 'Ces cookies sont utilisés pour fournir des publicités personnalisées.',
    'cookies.functional.title': 'Cookies Fonctionnels',
    'cookies.functional.desc': 'Ces cookies permettent des fonctionnalités améliorées et la personnalisation.',
    
    // Legal Pages SEO
    'privacy.seo.title': 'Politique de Confidentialité - Hibiscus Madeira',
    'privacy.seo.description': 'Lisez notre politique de confidentialité pour comprendre comment nous collectons, utilisons et protégeons vos informations personnelles chez Hibiscus Madeira.',
    'terms.seo.title': 'Conditions de Service - Hibiscus Madeira',
    'terms.seo.description': 'Consultez nos conditions de service pour comprendre les règles et directives d\'utilisation de notre site web et de réservation de nos appartements de luxe.',
    'cookiepolicy.seo.title': 'Politique des Cookies - Hibiscus Madeira',
    'cookiepolicy.seo.description': 'Découvrez comment nous utilisons les cookies pour améliorer votre expérience de navigation sur le site de Hibiscus Madeira.',
    'cancellation.seo.title': 'Politique d\'Annulation - Hibiscus Madeira',
    'cancellation.seo.description': 'Comprenez notre politique d\'annulation pour les réservations chez Hibiscus Madeira. Trouvez des détails sur les remboursements et les modifications.',

    // Legal Pages
    'privacy.title': 'Politique de Confidentialité',
    'privacy.lastupdated': 'Dernière mise à jour',
    'privacy.introduction.title': 'Introduction',
    'privacy.introduction.content': 'Chez Hibiscus Madeira, nous nous engageons à protéger votre vie privée et à assurer la sécurité de vos informations personnelles. Cette Politique de Confidentialité explique comment nous collectons, utilisons et protégeons vos données lorsque vous utilisez nos services.',
    'privacy.datacollection.title': 'Informations que Nous Collectons',
    'privacy.datacollection.intro': 'Nous collectons les informations que vous nous fournissez directement, comme lorsque vous :',
    'privacy.datacollection.personal': 'Informations d\'identification personnelle (nom, email, numéro de téléphone)',
    'privacy.datacollection.booking': 'Informations de réservation et de paiement',
    'privacy.datacollection.technical': 'Informations techniques (adresse IP, type de navigateur, informations sur l\'appareil)',
    'privacy.datacollection.communication': 'Préférences et historique de communication',
    'privacy.datause.title': 'Comment Nous Utilisons Vos Informations',
    'privacy.datause.intro': 'Nous utilisons les informations que nous collectons pour :',
    'privacy.datause.bookings': 'Traiter et gérer vos réservations',
    'privacy.datause.communication': 'Communiquer avec vous concernant vos réservations',
    'privacy.datause.improvement': 'Améliorer nos services et la fonctionnalité du site web',
    'privacy.datause.legal': 'Respecter les obligations légales',
    'privacy.datasharing.title': 'Partage d\'Informations',
    'privacy.datasharing.content': 'Nous ne vendons, n\'échangeons ou ne transférons pas vos informations personnelles à des tiers sans votre consentement, sauf comme décrit dans cette politique ou comme requis par la loi.',
    'privacy.cookies.title': 'Cookies et Suivi',
    'privacy.cookies.content': 'Nous utilisons des cookies et des technologies similaires pour améliorer votre expérience sur notre site web. Vous pouvez contrôler les préférences des cookies via notre bannière de consentement.',
    'privacy.rights.title': 'Vos Droits',
    'privacy.rights.intro': 'Sous les lois de protection des données applicables, vous avez le droit de :',
    'privacy.rights.access': 'Accéder à vos données personnelles',
    'privacy.rights.rectification': 'Rectifier les données inexactes',
    'privacy.rights.erasure': 'Demander la suppression de vos données',
    'privacy.rights.portability': 'Portabilité des données',
    'privacy.rights.objection': 'Vous opposer au traitement',
    'privacy.security.title': 'Sécurité des Données',
    'privacy.security.content': 'Nous mettons en œuvre des mesures techniques et organisationnelles appropriées pour protéger vos informations personnelles contre l\'accès non autorisé, l\'altération, la divulgation ou la destruction.',
    'privacy.contact.title': 'Contactez-nous',
    'privacy.contact.content': 'Si vous avez des questions sur cette Politique de Confidentialité ou nos pratiques de données, contactez-nous :',
    
    'terms.title': 'Conditions de Service',
    'terms.lastupdated': 'Dernière mise à jour',
    'terms.acceptance.title': 'Acceptation des Conditions',
    'terms.acceptance.content': 'En accédant et en utilisant les services d\'Hibiscus Madeira, vous acceptez et convenez d\'être lié par les termes et dispositions de cet accord.',
    'terms.services.title': 'Description des Services',
    'terms.services.content': 'Hibiscus Madeira fournit des services de location d\'appartements de luxe à Madère, Portugal, incluant la gestion des réservations, le support client et les services d\'hébergement.',
    'terms.bookings.title': 'Conditions de Réservation',
    'terms.bookings.intro': 'Lors d\'une réservation avec nous :',
    'terms.bookings.confirmation': 'Toutes les réservations sont soumises à disponibilité et confirmation',
    'terms.bookings.payment': 'Le paiement doit être effectué selon nos conditions de paiement',
    'terms.bookings.checkin': 'Les heures d\'arrivée et de départ doivent être respectées',
    'terms.bookings.checkout': 'Les propriétés doivent être laissées en bon état',
    'terms.cancellation.title': 'Politique d\'Annulation',
    'terms.cancellation.content': 'Les annulations sont soumises à notre politique d\'annulation, qui varie selon la propriété et le type de réservation. Veuillez consulter notre Politique d\'Annulation détaillée pour les conditions spécifiques.',
    'terms.conduct.title': 'Conduite des Invités',
    'terms.conduct.intro': 'Les invités sont tenus de :',
    'terms.conduct.respect': 'Respecter la propriété et les voisins',
    'terms.conduct.damage': 'Signaler tout dommage immédiatement',
    'terms.conduct.noise': 'Maintenir des niveaux de bruit raisonnables',
    'terms.conduct.smoking': 'Suivre les politiques de tabagisme',
    'terms.conduct.pets': 'Respecter les politiques concernant les animaux',
    'terms.liability.title': 'Limitation de Responsabilité',
    'terms.liability.content': 'La responsabilité d\'Hibiscus Madeira est limitée dans la mesure permise par la loi. Nous ne sommes pas responsables des dommages indirects, accessoires ou consécutifs.',
    'terms.intellectual.title': 'Propriété Intellectuelle',
    'terms.intellectual.content': 'Tout le contenu de notre site web, y compris le texte, les graphiques, les logos et les images, est la propriété d\'Hibiscus Madeira et protégé par les lois sur le droit d\'auteur.',
    'terms.governing.title': 'Loi Applicable',
    'terms.governing.content': 'Ces conditions sont régies par les lois du Portugal. Tout litige sera résolu devant les tribunaux de Madère, Portugal.',
    'terms.contact.title': 'Informations de Contact',
    'terms.contact.content': 'Pour des questions sur ces Conditions de Service, contactez-nous :',
    
    'cookiepolicy.title': 'Politique des Cookies',
    'cookiepolicy.lastupdated': 'Dernière mise à jour',
    'cookiepolicy.what.title': 'Que sont les Cookies ?',
    'cookiepolicy.what.content': 'Les cookies sont de petits fichiers texte qui sont placés sur votre appareil lorsque vous visitez notre site web. Ils nous aident à vous fournir une meilleure expérience en mémorisant vos préférences et en analysant comment vous utilisez notre site.',
    'cookiepolicy.types.title': 'Types de Cookies que Nous Utilisons',
    'cookiepolicy.types.necessary.title': 'Cookies Nécessaires',
    'cookiepolicy.types.necessary.content': 'Ces cookies sont essentiels au bon fonctionnement du site web. Ils permettent des fonctions de base comme la navigation et l\'accès aux zones sécurisées.',
    'cookiepolicy.types.analytics.title': 'Cookies d\'Analyse',
    'cookiepolicy.types.analytics.content': 'Ces cookies nous aident à comprendre comment les visiteurs interagissent avec notre site web en collectant et rapportant des informations de manière anonyme.',
    'cookiepolicy.types.marketing.title': 'Cookies Marketing',
    'cookiepolicy.types.marketing.content': 'Ces cookies sont utilisés pour diffuser des publicités plus pertinentes pour vous et vos intérêts.',
    'cookiepolicy.types.functional.title': 'Cookies Fonctionnels',
    'cookiepolicy.types.functional.content': 'Ces cookies permettent au site web de fournir des fonctionnalités améliorées et la personnalisation.',
    'cookiepolicy.manage.title': 'Gestion des Cookies',
    'cookiepolicy.manage.content': 'Vous pouvez contrôler et gérer les cookies via notre bannière de consentement ou les paramètres de votre navigateur. Notez que la désactivation de certains cookies peut affecter la fonctionnalité du site web.',
    'cookiepolicy.thirdparty.title': 'Cookies Tiers',
    'cookiepolicy.thirdparty.content': 'Certains cookies sont placés par des services tiers qui apparaissent sur nos pages. Nous ne contrôlons pas ces cookies.',
    'cookiepolicy.updates.title': 'Mises à Jour de cette Politique',
    'cookiepolicy.updates.content': 'Nous pouvons mettre à jour cette Politique des Cookies de temps en temps. Tout changement sera publié sur cette page avec une date de révision mise à jour.',
    'cookiepolicy.contact.title': 'Contactez-nous',
    'cookiepolicy.contact.content': 'Si vous avez des questions sur notre utilisation des cookies, contactez-nous :',
    
    'cancellation.title': 'Politique d\'Annulation',
    'cancellation.lastupdated': 'Dernière mise à jour',
    'cancellation.overview.title': 'Aperçu de la Politique',
    'cancellation.overview.content': 'Notre politique d\'annulation varie selon la propriété et le tarif sélectionné. Veuillez consulter les conditions d\'annulation spécifiques pour votre réservation.',
    'cancellation.standard.title': 'Politique d\'Annulation Standard',
    'cancellation.standard.subtitle': 'La plupart de nos propriétés suivent cette politique :',
    'cancellation.standard.free': 'Annulation gratuite jusqu\'à 48 heures avant l\'arrivée',
    'cancellation.standard.partial': '50% de remboursement pour les annulations 24-48 heures avant l\'arrivée',
    'cancellation.standard.norefund': 'Aucun remboursement pour les annulations dans les 24 heures de l\'arrivée',
    'cancellation.flexible.title': 'Politique d\'Annulation Flexible',
    'cancellation.flexible.subtitle': 'Disponible pour certaines propriétés :',
    'cancellation.flexible.free': 'Annulation gratuite jusqu\'à 24 heures avant l\'arrivée',
    'cancellation.flexible.partial': '50% de remboursement pour les annulations le jour même',
    'cancellation.strict.title': 'Politique d\'Annulation Stricte',
    'cancellation.strict.subtitle': 'S\'applique en haute saison et événements spéciaux :',
    'cancellation.strict.partial': '50% de remboursement pour les annulations jusqu\'à 7 jours avant l\'arrivée',
    'cancellation.strict.norefund': 'Aucun remboursement pour les annulations dans les 7 jours de l\'arrivée',
    'cancellation.process.title': 'Comment Annuler',
    'cancellation.process.step1': 'Contactez-nous par email ou téléphone dès que possible',
    'cancellation.process.step2': 'Fournissez votre numéro de référence de réservation',
    'cancellation.process.step3': 'Nous confirmerons l\'annulation et le remboursement applicable',
    'cancellation.process.step4': 'Les remboursements sont traités dans les 5-10 jours ouvrables',
    'cancellation.exceptions.title': 'Circonstances Exceptionnelles',
    'cancellation.exceptions.content': 'Nous pouvons renoncer aux frais d\'annulation en cas de :',
    'cancellation.exceptions.weather': 'Conditions météorologiques sévères',
    'cancellation.exceptions.emergency': 'Urgences médicales',
    'cancellation.exceptions.government': 'Restrictions de voyage imposées par le gouvernement',
    'cancellation.modifications.title': 'Modifications de Réservation',
    'cancellation.modifications.content': 'Les modifications aux réservations existantes sont soumises à disponibilité et peuvent entraîner des frais supplémentaires. Contactez-nous pour discuter des options de modification.',
    'cancellation.contact.title': 'Besoin d\'Aide ?',
    'cancellation.contact.content': 'Pour les annulations ou questions sur notre politique, contactez-nous :',
    'cancellation.contact.hours': 'Heures d\'Ouverture'
  }
};